wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707325826.560523
    t:
      1:
      - 1
      - 9
      - 55
      - 77
      - 103
      2:
      - 1
      - 9
      - 55
      - 77
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
